version: '3'

networks:
  localnet:
    driver: overlay

services:

  redis:
    image: redis:3.2.9-alpine
    networks:
      - localnet
    deploy:
      mode: replicated
      replicas: 1

  vaadin-session-clustered:
    image: vaadin-session-clustered:latest
    ports:
      - "8080:8080"
    networks:
      - localnet
    deploy:
      mode: replicated
      replicas: 1
    command:
      - "--spring.redis.host=redis"
